[ERROR] (tests/ex29_tests.c:34:main: errno-> None) Function fail_on_purpose return 1 for data: peter
